name: MineSkyGuildas2
version: '1.0.2-ALPHA'
main: net.mineskyguildas.MineSkyGuildas
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - WorldGuard
authors: [zBrunoC (Bruno C.)]

commands:
  guildas:
    description: Comandos para gerenciar guildas
    usage: /guilda <subcomando>
    aliases: [ guilds,guild,guilda, msguilda, msguild ]
  .:
    description: Comando de chat da guilda.
    usage: /. <mensagem>
    aliases: [ mgchat ]
  ally:
    description: Comando de chat de aliados.
    usage: /ally <mensagem>
    aliases: [ mgally,aliado,aliados ]
  líderes:
    description: Comando para um chat exclusivo dos líderes da guilda.
    usage: /líderes <mensagem>
    aliases: [lider,líder,lideres]

permissions:
  mineskyguildas.kdr.exclude:
    description: Permissão de excluir do sistema de KDR.
    default: false
  mineskyguildas.reload:
    description: Pode reiniciar as configurações e reconectar o MongoDB das guildas.
    default: op
  mineskyguildas.spy:
    description: Pode ver as mensagens das guildas no Chat da guildas e dos aliados.
    default: op
  mineskyguildas.admin:
    description: Todas as permissões do plugin.
    default: op
    children:
      mineskyguildas.spy: true
      mineskyguildas.reload: true